### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by daloisop** [JonRobo/robopython#6]
Hi,
yesterday I was able to connect withe the USB dongle to the Robo and I was able to run all of your provided demo scripts.

Todaynothing is working anymore...

For example if I want to run this:

```
from robopython import Robo

BLE_Name = "ROBO"
Robo = Robo(BLE_Name)
print Robo.battery_level()
```

I receive the following:

PS C:\Users\Patrick> & C:/Python27/python.exe c:/Users/Patrick/Documents/robo_test1.py
Running on Windows, please ensure your BLED112 dongle is plugged in
Traceback (most recent call last):
  File "c:/Users/Patrick/Documents/robo_test1.py", line 4, in <module>
    Robo = Robo(BLE_Name)
  File "C:\Python27\lib\site-packages\robopython\robopython.py", line 44, in __init__
    self.BLE = BLED112(self.name, com_port)
  File "C:\Python27\lib\site-packages\robopython\ble_robo.py", line 28, in __init__
    self.connect_ble()
  File "C:\Python27\lib\site-packages\robopython\ble_robo.py", line 110, in connect_ble
    self.scan()
  File "C:\Python27\lib\site-packages\robopython\ble_robo.py", line 84, in scan
    devices = self.adapter.scan()
  File "C:\Python27\lib\site-packages\robopython\pygatt\backends\bgapi\bgapi.py", line 328, in scan
    self.expect(ResponsePacketType.gap_end_procedure)
  File "C:\Python27\lib\site-packages\robopython\pygatt\backends\bgapi\bgapi.py", line 534, in expect
    return self.expect_any([expected], *args, **kargs)
  File "C:\Python27\lib\site-packages\robopython\pygatt\backends\bgapi\bgapi.py", line 582, in expect_any
    self._packet_handlers[packet_type](response)
  File "C:\Python27\lib\site-packages\robopython\pygatt\backends\bgapi\bgapi.py", line 709, in _ble_evt_gap_scan_response
    name, data_dict = self._scan_rsp_data(args['data'])
  File "C:\Python27\lib\site-packages\robopython\pygatt\backends\bgapi\bgapi.py", line 508, in _scan_rsp_data
    constants.scan_response_data_type[field_value[0]])
KeyError: 38

The same happens if I try it on my MacBook (where it was working yesterday)

Do you have a tip for me what could be wrong ?

**Comment by JonRobo** [comment]
Hello @daloisop Sorry for the late reply
I have pushed an update, this should help. Another thing may be to try to name your Robo instance something other than Robo since this is the class name there may be confusion. There are some demos available to try in this repo. Please let me know if you still have this issue.
